short_name: "Continuous Deployment for RAI"
title: "Continuous Deployment for RAI"
version: "2023"
publisher: "CSIRO Data61"
source_url: "https://research.csiro.au/ss/science/projects/responsible-ai-pattern-catalogue/"
licence: "CC-BY-4.0"
redistributable: true
